service: petshop3219

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  memorySize: 128
  timeout: 10
  environment:
    NODE_ENV: production

functions:
  server:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true
package:
  exclude:
    - images/**